/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/renderer/index.html', './src/renderer/src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['SF Mono', 'Fira Code', 'Menlo', 'Consolas', 'monospace'],
      },
      colors: {
        'bg-primary':    'var(--color-bg-primary)',
        'bg-secondary':  'var(--color-bg-secondary)',
        'bg-tertiary':   'var(--color-bg-tertiary)',
        'bg-surface':    'var(--color-bg-surface)',
        'bg-elevated':   'var(--color-bg-elevated)',
        'text-primary':  'var(--color-text-primary)',
        'text-secondary':'var(--color-text-secondary)',
        'text-muted':    'var(--color-text-muted)',
        'text-inverse':  'var(--color-text-inverse)',
        border:          'var(--color-border)',
        'border-subtle': 'var(--color-border-subtle)',
        'border-focus':  'var(--color-border-focus)',
        accent:          'var(--color-accent)',
        'accent-hover':  'var(--color-accent-hover)',
        'accent-subtle': 'var(--color-accent-subtle)',
        success:         'var(--color-success)',
        'success-subtle':'var(--color-success-subtle)',
        warning:         'var(--color-warning)',
        'warning-subtle':'var(--color-warning-subtle)',
        danger:          'var(--color-danger)',
        'danger-subtle': 'var(--color-danger-subtle)',
        info:            'var(--color-info)',
        'info-subtle':   'var(--color-info-subtle)',
        'priority-high':   'var(--color-priority-high)',
        'priority-medium': 'var(--color-priority-medium)',
        'priority-low':    'var(--color-priority-low)',
      },
      fontSize: {
        '2xs': ['10px', '14px'],
        xs:    ['11px', '16px'],
        sm:    ['13px', '20px'],
        base:  ['14px', '22px'],
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
